### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by mistrysiddh** [akiritsu/pRoJEct-VeXEd#1]
how to add or change encrypted text.

**Comment by gmkzwwg** [comment]
See https://github.com/akiritsu/pRoJEct-NeGYa/issues/2 for generating encrypted text or decrypting them.
In my scheme I put the encrypted code in the id property, decrypt it, and replace the content with decrypted message. Here is the code:
```
<p class="encrypted"
 id="/MZAf/PKx9jpw8/Jnp7XQQFki2ibGnArZP46W+keVThXquhWwFROEFnbY8eC57Tw=="
>
Encrypted content!
</p>
```

**Comment by KoalaWSMTW** [comment]
Hi, thanks for this awesome theme !

I don't understand how encrypted text work.

in the id parameter you set the IV and the SALT ?  Separated with / ?

With the [SCJL DEMO](https://bitwiseshiftleft.github.io/sjcl/demo/) i cannot reverse your ID specifed in defaut template ?
