### ISSUE TITLE
encrypted text

### ISSUE THREAD

**Issue by andrigamerita** [akiritsu/pRoJEct-VeXEd#2]
How do you create new encrypted text to put on the homepage? And how do you change the token?

**Comment by ironWolf1990** [comment]
I have the same problem. I encrypted the text with a password, took the minimised text and pasted it in the format u specified. But whenever I try to decrypt the text on the page with the token is say "Invalid Token"

**Comment by mistrysiddh** [comment]
the same issue i have

**Comment by gmkzwwg** [comment]
Sorry for late reply.
You can build a personal encrypting & decrypting tool by scripts below, or simply use tools on http://bitwiseshiftleft.github.io/sjcl/demo/ or http://bcqlr.com/sjcl/.

```
  function encrypt() {
    var pwd = document.getElementById("pwd").value;
    var msg = document.getElementById("msg").value;
    var ct =  sjcl.json.encrypt(pwd, msg,{salt: ""});
    var ct_obj = JSON.parse(ct);
    document.getElementById("ct").value = ct;
    document.getElementById("msg").value = "";
    document.getElementById("min_text").value = (ct_obj.iv.substring(0,22) + ct_obj.ct);
  }
  function decrypt() {
    var pwd = document.getElementById("pwd").value;
    var ct = document.getElementById("ct").value;
    document.getElementById("msg").value = sjcl.json.decrypt(pwd, ct);
    document.getElementById("ct").value = "";
    document.getElementById("min_text").value = "";
  }
```
