### ISSUE TITLE
encryption on post entries

### ISSUE THREAD

**Issue by d3aths** [akiritsu/pRoJEct-VeXEd#4]
any way to get encryption to work on the posts page? when you click on an entry, ive got some encrypted text there but on the actual post page itself there's nowhere to enter an access token

**Comment by d3aths** [comment]
figured out now to just include 
`encrypted_text: true` in the post variables, and now the box for the access token will appear, but it says the token is invalid even though its not.
using a fresh minimized code and everything from http://bcqlr.com/sjcl/

**Comment by d3aths** [comment]
appears to be working with further refreshing the server and tried a new code - caused by delay in server updating :)

**Comment by gmkzwwg** [comment]
Good luck and have fun!
