### ISSUE TITLE
change order of "collections"

### ISSUE THREAD

**Issue by ghost** [akiritsu/pRoJEct-VeXEd#5]
Hi man, in those days I was able to build the website for my project( https://baseband-processor.github.io/WirelessLegacy.github.io/)
so for first thing, thanks!

Now I was trying to change the order of various "collection" under the voice archive because I hate to see the "Frequently asked question"  up to the stack, any helps?

Essentially I would like to known how I could change the order of collection items without following the alphabetic order.

Edoardo Mantovani, 2020

**Comment by gmkzwwg** [comment]
Thanks for your questions.

The order of collection items is essentially in the order of {{site.collections}}, it is determined by some Jekyll stuff.

To reorder them is easy:
keep the order of these items into a array in _config.yml, then change /src/_includes/collection_list.html. From line 56 on, iterate the array and choose the right item to be shown. 

I really think this request is useful, so thank you and I'll start to work on it immediately.  Don't forget check it out~

DeerRIDER.

**Comment by gmkzwwg** [comment]
I've work it out. Check out the latest update~

You can now specify the order of collection items with rewrite "collection_order" in _config.yml.

Good luck and have fun!

**Comment by ghost** [comment]
Ok thanks!
I arranged myself renaming every section with an alphabetic letter and then I used the alias keyword

Regards
Edoardo Mantovani, 2020

**Comment by gmkzwwg** [comment]
Hahaha, smart man, it is really a nice way to do this.
Using "collection_order" could make it more clear-cut, and it is easier to re-order or inserting new collection items.

**Comment by ghost** [comment]
Ok, I'll remember that!

Edoardo Mantovani, 2020
