### ISSUE TITLE
Use links instead of words in collections

### ISSUE THREAD

**Issue by ghost** [akiritsu/pRoJEct-VeXEd#6]
Hi again,

I was trying to set up a direct link in my _config.yml file, so instead of
```shell
Collections:
  Suggested_libraries:
    output          : true
    permalink       : /:collection/:title/
    alias           : "Suggested Libraries"
    order:
      - Socket.md
      - Net::Pcap
      - Net::Ncap
      - Net::Frame.md
      - NetPacket.md
      - Net::Write.md
      - Net::Analysis.md
      - Net::Silk.md
      - Net::Inspect.md
      - Net::Tshark.md
      - Net::Sharktools.md
      - File::PCAP.md

```

I would like to have something like:

```ollections:
  Suggested_libraries:
    output          : true
    permalink       : /:collection/:title/
    alias           : "Suggested Libraries"
    order:
      - [Socket.md](my_url)

```

which works ( the _config.yml file regist an error when I try to set up the link).
Thanks

Edoardo Mantovani, 2020

**Comment by gmkzwwg** [comment]
Hi,
Sorry exactly i don't understand what you need.

Do you mean you wish to keep the order information into the file "Socket.md"? Or show a link "my_url" and rename it to "Socket.md", list it in "Suggested Libraries"?

To the first question, Jekyll won't access links in _config.yml by any way, it can only keep it as a post object.

To the second question, maybe it can be resolved by redirecting. Do create "Socket.md" under "_suggested_libraries", and write the htmls below:

```
<html>
<head>
</head>
<meta http-equiv="refresh" content="0.01'; url="my_url">
<body>
</body>
</html>
```

**Comment by ghost** [comment]
Hi!
Don't  worry just an old question :)

One thing which would be really cool could be the implementation of a simplified interface of  https://threatmap.checkpoint.com/ in a format like a world-real-time gif.
When I'll have some free time I think I'll try to implement something in which could accomplish this in perl.

Edoardo Mantovani, 2020

**Comment by gmkzwwg** [comment]
Okay, that website is really amazing!
If you need more help, feel free to contact me.

**Comment by ghost** [comment]
Yeah, it would be really cool to add like an option in markdown intestation for showing the real time attacks-map.

Edoardo Mantovani, 2020
